[versions]
neoforge = "21.11.25-beta"
mdg = "2.0.139"
neoforgeRange = { require = "[21.11.25-beta,)", prefer = "21.11.25-beta" }
loaderRange = { require = "[4,)", prefer = "4" }

#[libraries.testframework]
#module = "net.neoforged:testframework"
#version.ref = "neoforge"

[plugins.moddev]
id = "net.neoforged.moddev"
version.ref = "mdg"
